<?php
/**
 * This Template is for Displaying Home Page
 */

 get_header(); ?>

<style>
    .row {
        margin: 15px;
    }
    .row a {
        margin-bottom: 20px;
    }
    img {
        object-fit: cover;
        height: 220px;
        width: 300px;
    }
    #gallery-content {
        display: flex;
        flex-wrap: wrap;
    }
    .gallery-item {
        display: none;
        opacity: 0;
        
    }
    #gallery-content .gallery-item.visible {
        display: block;
        opacity: 1;
        transition: opacity 0.5s ease-in-out;
    }
    .all-btns{
        display:flex;
        justify-content: space-between;
    }

</style>



<section class="main-gallery">
    <div class="container" id="image-gallery">
        <div class="row" id="gallery-content">
            <!-- Assuming this is dynamically generated by WordPress PHP -->
            <?php
                if (have_rows('gallery_repeater', 8)) {
                    while (have_rows('gallery_repeater', 8)) {
                        the_row();
                        $image = get_sub_field('images', 8);
                        ?>
            <a href="<?php echo esc_url($image); ?>" data-toggle="lightbox" data-gallery="gallery"
                class="col-md-4 gallery-item">
                <img src="<?php echo esc_url($image); ?>">
            </a>
            <?php
                    }
                }
                ?>
        </div>
        <div id="load-more-less-buttons" class="all-btns">
            <div id="load-more-wrapper">
                <button id="load-more-images" class="btn btn-primary my-3">Load More</button>
            </div>
            <div id="load-less-wrapper" style="display:none;">
                <button id="load-less-images" class="btn btn-primary my-3">Load Less</button>
            </div>
        </div>
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
$(document).ready(function() {
    var itemsToShow = 6;
    var totalItems = $('.gallery-item').length;
    var itemsVisible = itemsToShow;

    function updateGallery() {
        $('.gallery-item').each(function(index) {
            if (index < itemsVisible) {
                $(this).fadeIn(1000).addClass('visible');
            } else {
                $(this).fadeOut(1000).removeClass('visible');
            }
        });
    }

    function toggleButtons() {
        if (itemsVisible >= totalItems) {
            $('#load-more-wrapper').hide();
            $('#load-less-wrapper').show();
        } else {
            $('#load-more-wrapper').show();
        }

        if (itemsVisible <= itemsToShow) {
            $('#load-less-wrapper').hide();
        } else {
            $('#load-less-wrapper').show();
        }
    }

    function scrollToItem(itemIndex) {
        var target = $('.gallery-item').eq(itemIndex);
        $('html, body').animate({
            scrollTop: target.offset().top
        }, 800);
    }

    updateGallery();
    toggleButtons();

    // Load more button click event
    $('#load-more-images').click(function() {
        var prevItemsVisible = itemsVisible;
        itemsVisible += itemsToShow;
        if (itemsVisible > totalItems) {
            itemsVisible = totalItems;
        }
        updateGallery();
        toggleButtons();
        if (itemsVisible > prevItemsVisible) {
            scrollToItem(prevItemsVisible);
        }
    });

    // Load less button click event
    $('#load-less-images').click(function() {
        var prevItemsVisible = itemsVisible;
        itemsVisible -= itemsToShow;
        if (itemsVisible < itemsToShow) {
            itemsVisible = itemsToShow;
        }
        updateGallery();
        toggleButtons();
        if (itemsVisible < prevItemsVisible) {
            scrollToItem(itemsVisible - 1);
        }
    });
});


</script>




<script>
$(document).on("click", '[data-toggle="lightbox"]', function(event) {
    event.preventDefault();
    $(this).ekkoLightbox();
});
</script>

<?php
get_footer();?>